name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:

  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy FTP
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: "ftp://ftp.lokuswp.com/lwpcommerce/"
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

    # - name: Deploy Notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,job,took # selectable (default: repo,message)
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHANNEL }} # required
    #     MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
    #   if: always()