name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:

  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy to Development
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: "ftp://${{ secrets.LWC_FTP_HOST }}/plugins/lwcommerce/"
          user: ${{ secrets.LWC_FTP_USERNAME }}
          password: ${{ secrets.LWC_FTP_PASSWORD }}
