# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
name: Deploy to Production

on:
  push:
    branches:
      - "RC-[0-9].[0-9].[0-9]" # RC-1.1.1

jobs:

  deploy-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build project
        run: |
          mkdir ${{ github.event.repository.name }}
          cp -r src ${{ github.event.repository.name }}/src
          cp ${{ github.event.repository.name }}.php ${{ github.event.repository.name }}/${{ github.event.repository.name }}.php
          cp uninstall.php ${{ github.event.repository.name }}/uninstall.php
          cp CHANGELOG.md ${{ github.event.repository.name }}/CHANGELOG.md
          cp LICENSE ${{ github.event.repository.name }}/LICENSE
          ls ${{ github.event.repository.name }}/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: ${{ github.event.repository.name }}
            path: ${{ github.event.repository.name }}/
            if-no-files-found: error

      - name: Deploy FTP
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: "ftp://demo.lokuswp.id/lwpcommerce"
          user: ${{ secrets.DEMO_USERNAME }}
          password: ${{ secrets.DEMO_PASSWORD }}
          syncroot: ${{ github.event.repository.name }}/