name: Pre Release
on:
  release:
    types: [ published ]
jobs:
  build:
    if: "github.event.release.prerelease"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Push Notification
        uses: distributhor/workflow-webhook@v2
          env:
            webhook_url: https://webhook.site/9302ad64-9a1f-4292-a1a1-c97d586ccb94
            data: '{ "new update": "LWCommerce" }'